services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures file watching works inside Docker
      - REACT_APP_HLS_URL=https://d1n905ucw43ysc.cloudfront.net/output/hls/sample.m3u8
      #- REACT_APP_HLS_URL=https://awstesting-output-bucket.s3.us-east-2.amazonaws.com/output/hls/sample.m3u8
    volumes:
      - .:/app   # Mount the current directory to the container
      - /app/node_modules  # Prevent node_modules from being overwritten
    stdin_open: true  # Allow interactive input
    tty: true  # Keep the container running
    restart: unless-stopped
