services:
  aws-cli:
    #image: amazon/aws-cli:latest
    build: .
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_PROJECT_ID: ${AWS_PROJECT_ID}
      MEDIACONVERT_ENDPOINT: ${MEDIACONVERT_ENDPOINT}
      MEDIACONVERT_JOB_TEMPLATE: ${MEDIACONVERT_JOB_TEMPLATE}
      MEDIACONVERT_ROLE_ARN: ${MEDIACONVERT_ROLE_ARN}
      MEDIACONVERT_QUEUE_ARN: ${MEDIACONVERT_QUEUE_ARN}
      BUCKET_INPUT: ${BUCKET_INPUT}
      BUCKET_OUTPUT: ${BUCKET_OUTPUT}
      BUCKET_DEFAULT: ${BUCKET_DEFAULT}
      SNS_NAME_MEDIACONVERT: ${SNS_NAME_MEDIACONVERT}
      CLOUDWATCH_RULE_NAME: ${CLOUDWATCH_RULE_NAME}
      LAMBDA_FUNCTION_NAME: ${LAMBDA_FUNCTION_NAME}
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/bin/sh", "/scripts/run.sh"]

  lambda:
    build: ./scripts/lambda
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      LAMBDA_FUNCTION_NAME: ${LAMBDA_FUNCTION_NAME}
      LAMBDA_EXECUTION_ROLE: ${LAMBDA_EXECUTION_ROLE}
    volumes:
      - ./scripts/lambda/:/scripts/
    entrypoint: ["/bin/bash", "/scripts/run-tests-and-upload.sh"]
