services:
  aws-cli:
    #image: amazon/aws-cli:latest
    build: .
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      MEDIACONVERT_ENDPOINT: ${MEDIACONVERT_ENDPOINT}
      MEDIACONVERT_JOB_TEMPLATE: ${MEDIACONVERT_JOB_TEMPLATE}
      MEDIACONVERT_ROLE_ARN: ${MEDIACONVERT_ROLE_ARN}
      CLOUDFRONT_ORIGIN_PATH: ${CLOUDFRONT_ORIGIN_PATH}
      CLOUDFRONT_DEFAULT_ROOT_OBJECT: ${CLOUDFRONT_DEFAULT_ROOT_OBJECT}
      BUCKET_INPUT: ${BUCKET_INPUT}
      BUCKET_OUTPUT: ${BUCKET_OUTPUT}
      BUCKET_DEFAULT: ${BUCKET_DEFAULT}
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/bin/sh", "/scripts/run.sh"]
