services:
  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"

  spark-worker-1:
    image: bitnami/spark:3.5
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    working_dir: /app
    depends_on:
      - spark-master
    volumes:
      - ./app:/app

  spark-worker-2:
    image: bitnami/spark:3.5
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    working_dir: /app
    depends_on:
      - spark-master
    volumes:
      - ./app:/app

  spark-submit:
    image: bitnami/spark:3.5
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    environment:
      - SPARK_MODE=client
      - SPARK_MASTER_URL=http://spark-master:8080
      - EXPECTED_WORKERS=2
    working_dir: /app
    volumes:
      - ./app:/app
      - ./requirements.txt:/app/requirements.txt
      - ./wait-for-spark.sh:/opt/bitnami/scripts/wait-for-spark.sh
    command: >
      bash -c "
      pip install -r requirements.txt;
      /opt/bitnami/spark/bin/spark-submit
      --master spark://spark-master:7077
      --conf spark.driver.extraJavaOptions=\"-Duser.home=/tmp\"
      --conf spark.executor.extraJavaOptions=\"-Duser.home=/tmp\"
      /app/main.py"

