services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: your_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - elk_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/mysql-connector-j-9.0.0.jar:/usr/share/logstash/mysql-connector-j-9.0.0.jar
    depends_on:
      - mysql
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_DB: your_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_TABLE: products
      ELASTIC_HOST: elasticsearch
      ELASTIC_PORT: 9200
      ELASTIC_INDEX: your_index_name
    networks:
      - elk_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elk_network

  golang:
    image: golang:1.19
    container_name: golang_app
    volumes:
      - ./golang:/app
    working_dir: /app
    command: go run main.go
    depends_on:
      - elasticsearch
    environment:
      ELASTIC_HOST: elasticsearch
      ELASTIC_PORT: 9200
      ELASTIC_INDEX: your_index_name
    networks:
      - elk_network
    ports:
      - "8080:8080"
  
  cronjob:
    build: cronjob/.
    container_name: product_inserter
    depends_on:
      - mysql
    networks:
      - elk_network

networks:
  elk_network:

volumes:
  mysql_data:
  es_data:
